id: P010493
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-19 20:52:37.987850
source_metadata:
  id: bdr:W1EE5
  title: ཇིརུཀེན-ཨུ་ཏོལྟ-ཡིན་ཏཡིལྦུརི
  author: ''
  volumes:
    5b0fbc0f4b7c45d69c8d835caeb02c75:
      image_group_id: I1KG16828
      title: ''
      volume_number: 1
      total_pages: 36
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
